export const theme = {
  font: "'IBM Plex Sans Arabic', 'Cairo', system-ui, -apple-system, sans-serif",
  colors: {
    deep: "#0b1d3f",
    mid: "#0f2f63",
    accent: "#00bfa6",
    accentAlt: "#ffc861",
    card: "#ffffff",
    bg: "#f7f8fb",
    border: "#dfe5f1",
    muted: "#6b7280",
    text: "#111827",
  },
  radius: 18,
  shadow: "0 12px 30px rgba(11, 29, 63, 0.12)",
};

export const styles = {
  page: {
    minHeight: "100vh",
    background: `linear-gradient(180deg, ${theme.colors.deep} 0%, ${theme.colors.mid} 26%, ${theme.colors.bg} 26%)`,
    padding: "18px 14px 32px",
    color: theme.colors.text,
    fontFamily: theme.font,
  },
  shell: {
    maxWidth: 540,
    margin: "0 auto",
  },
  headerCard: {
    background: "linear-gradient(135deg, #10356f 0%, #0b1d3f 70%)",
    color: "#fff",
    borderRadius: theme.radius + 4,
    padding: "18px 16px 20px",
    boxShadow: theme.shadow,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  miniLabel: {
    margin: 0,
    fontSize: 12,
    letterSpacing: "0.04em",
    color: "rgba(255,255,255,0.85)",
  },
  title: {
    margin: "4px 0 0",
    fontSize: 26,
    fontWeight: 700,
  },
  subtitle: {
    margin: "6px 0 0",
    color: "rgba(255,255,255,0.78)",
    fontSize: 14,
    lineHeight: 1.6,
  },
  envBadge: {
    background: "rgba(255,255,255,0.12)",
    border: "1px solid rgba(255,255,255,0.18)",
    color: "#fff",
    borderRadius: 12,
    padding: "8px 12px",
    fontSize: 12,
    whiteSpace: "nowrap",
  },
  card: {
    background: theme.colors.card,
    borderRadius: theme.radius,
    padding: "18px 16px",
    marginTop: 14,
    boxShadow: "0 10px 24px rgba(5, 19, 48, 0.06)",
    border: "1px solid #e9eef7",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 10,
  },
  blockTitle: {
    margin: "2px 0 0",
    fontSize: 18,
    fontWeight: 700,
    color: theme.colors.text,
  },
  amountPill: {
    background: "#f5f7fb",
    border: `1px solid ${theme.colors.border}`,
    padding: "8px 12px",
    borderRadius: 12,
    fontSize: 13,
    fontWeight: 600,
    color: theme.colors.mid,
    whiteSpace: "nowrap",
  },
  label: {
    fontWeight: 700,
    fontSize: 14,
    marginBottom: 6,
    color: theme.colors.text,
  },
  hint: {
    margin: "6px 0 0",
    fontSize: 12,
    color: theme.colors.muted,
  },
  inputShell: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "#f5f7fb",
    border: `1px solid ${theme.colors.border}`,
    borderRadius: 14,
    padding: "0 10px",
    marginTop: 8,
  },
  inputPrefix: {
    fontWeight: 700,
    fontSize: 13,
    color: theme.colors.mid,
    padding: "0 6px",
  },
  input: {
    flex: 1,
    border: "none",
    background: "transparent",
    padding: "12px 8px",
    fontSize: 17,
    outline: "none",
    direction: "ltr",
    textAlign: "left",
  },
  chipGroup: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 8,
    marginTop: 8,
  },
  chip: {
    borderRadius: 12,
    padding: "12px 10px",
    border: `1px solid ${theme.colors.border}`,
    fontSize: 15,
    fontWeight: 700,
    background: "#f9fafb",
    color: theme.colors.text,
    cursor: "pointer",
  },
  chipActive: {
    background: "linear-gradient(135deg, #00c8ad 0%, #0f8a9a 100%)",
    color: "#fff",
    border: "none",
    boxShadow: "0 8px 20px rgba(0, 136, 150, 0.35)",
  },
  row: {
    padding: "10px 0",
    borderBottom: `1px dashed ${theme.colors.border}`,
  },
  rowTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  rowLabel: {
    fontWeight: 700,
    color: theme.colors.text,
  },
  rowSub: {
    color: theme.colors.muted,
    marginTop: 2,
    fontSize: 12.5,
  },
  rowValue: {
    fontWeight: 800,
    color: theme.colors.mid,
    whiteSpace: "nowrap",
  },
  progressTrack: {
    marginTop: 8,
    width: "100%",
    height: 8,
    background: "#eef2fb",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    borderRadius: 999,
    background: "linear-gradient(90deg, #2563eb 0%, #00bfa6 100%)",
  },
  summaryRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingTop: 12,
  },
  pill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 12px",
    background: "#0b1d3f",
    color: "#fff",
    borderRadius: 12,
    fontSize: 13,
    fontWeight: 700,
  },
  list: {
    display: "grid",
    gap: 10,
    marginTop: 10,
  },
  listItem: {
    background: "#f6f8fc",
    borderRadius: 12,
    padding: "12px 12px",
    border: `1px solid ${theme.colors.border}`,
  },
  empty: {
    textAlign: "center",
    color: theme.colors.muted,
    padding: "8px 0 4px",
    fontSize: 14,
  },
  closeBtn: {
    width: "100%",
    marginTop: 12,
    padding: "14px 12px",
    borderRadius: 14,
    border: `1px solid ${theme.colors.border}`,
    background: "#ffffff",
    color: theme.colors.mid,
    fontWeight: 800,
    fontSize: 15,
    cursor: "pointer",
  },
};
